### ISSUE TITLE
Date format in datepicker

### ISSUE THREAD

**Issue by DaanWeller** [dankmitchell/spina-articles#4]
The format that the bootstrap datepicker uses defaults to mm/dd/yyyy on my app. Articles are not saved and no error message is shown. Note that the app does view a message about the search engines not being able to find the website. Entering the dd/mm/yyyy format manually does work. 

I'm new to rails and webdevelopment in general so I might be making a newbie mistake here, as I don't know where to change the date format for the datepicker. Either way, no error message is shown which is undesireable. Any thoughts?

Unrelated: thanks for this nice addition to Spina! :)

**Comment by dankmitchell** [comment]
Thanks for raising this @DaanWeller, pushed a PR to Spina now.

**Comment by dankmitchell** [comment]
Done. You'll have to use the master branch of Spina but its stable. 

https://github.com/denkGroot/Spina/commit/7358b8ff252256ff92cd248e05b350b4dac5db58
